### ISSUE TITLE
Add support for jenkins secret files

### ISSUE THREAD

**Issue by uscengineer** [rochacbruno/dynaconf#117]
My settings.json file is stored in jenkins as a secret file which can be read as an environment variable. At this time only way to make it work is to cat the secret file into settings.json but that defeats the purpose of the secret file.

**Comment by rochacbruno** [comment]
We can implement that, I just need to know about how this should work. We already have the `ENVVAR_FOR_DYNACONF`  settings, I guess if changing it to the name of the jenkins env var will work.

**Comment by uscengineer** [comment]
Once you upload the settings.json file to Jenkins you can access it by giving it any name:
![image](https://user-images.githubusercontent.com/4692975/52998487-40863300-33d8-11e9-92e1-6b7c7e729017.png)

How about adding it to the loading order? Can't use a period in the env var but can you make it look for env var **SETTINGS** or **settings**?

**Comment by rochacbruno** [comment]
Now it is possible to export SECRETS_FOR_DYNACONF and have this
extra point loaded, like in a Jenkins CI you can specify on job.

```yaml
secret_file:
  variable: SECRETS_FOR_DYNACONF
  credentials:
    type: specific_credentials
    value: /path/to/secrets_file.toml{json,ini,yaml,py}

```

That variable can also be a list of paths.
