### ISSUE TITLE
RFC: Template Substitutions - dynaconf-render-template plugin

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#145]
Require: #146 

## Allow template substitutions

There are 2 types of variables that would be useful to have access within dynaconf settings

- Environment Variables `${HOME}`, `${PWD}`
- Dynaconf variables `settings.get('value')`, `settings.ROOT_PATH_FOR_DYNACONF`

When setting a new variable it would be nice to have access to that vars like using special marker `$D{}` or `@D{}` (to be defined).

To avoid overhead, this feature must be enabled via plugin.

```python
pip install dynaconf-template-render
```

```yaml
default:
  databases:
    default:
      name: foo_database
      driver: sqlite3
      file: $D{ROOT_PATH_FOR_DYNACONF}/foo.db
   conf_location: $D{HOME}/.config/foo/  
```

Then after executing the loaders (the bottom of `.execute_loaders` method) there will be a `plugin_hook` which will be called having `obj` on context, then plugin can make changes to `obj` (in place)
