### ISSUE TITLE
`dynaconf_merge` doesn't appear to work on Jupyter notebook

### ISSUE THREAD

**Issue by AshishShanker** [rochacbruno/dynaconf#147]
I am on Jupyter notebook through Anaconda distribution on Windows 10.
```
from platform import python_version
python_version()
# yields 3.7.1
```
Here are my files:
```
#.env
# empty file; I also tried ENV_FOR_DYNACONF="DEVELOPMENT" but that doesn't make any difference
#.secrets.yaml
development:
  section1:
    fieldA: "abc"
    fieldB: "bcd"
    fieldC: 1
    host: "11.11.11.11" # fake host
    dynaconf_merge: true

# settings.yaml
default:
  section1:
    scheme: "http"
    base_url: "some.site.com/REST"
```
Here is the code and output I get:
```
from dynaconf import settings
config = settings.get("SECTION1")
print(settings.current_env)
print(config)

# Output:
DEVELOPMENT
{'FieldA' : 'abc', 'FieldB' : 'bcd', 'FieldC' : 1, 'host' : '11.11.11.11', 'dynaconf_merge' : True }

# Expected
DEVELOPMENT
{'FieldA' : 'abc', 'FieldB' : 'bcd', 'FieldC' : 1, 'host' : '11.11.11.11', 'scheme' : 'http', 'base_url' : 'some.site.com/REST' }
```

So it appears the settings loader isn't able to recognize `dynaconf_merge` as one of its special markers and is simply passing it out as a field of the settings object requested. So obviously, no merge is happening either.
