### ISSUE TITLE
Export merged environment to yaml

### ISSUE THREAD

**Issue by austinnichols101** [rochacbruno/dynaconf#200]
I'm looking for a way to "flatten" the settings into a single `values.yaml` file from the following `settings.yaml`.  

Assume that `ENV_FOR_DYNACONF=development`

```
global:
  a: 1
 
default:
  b: 2

development: 
  foo:
    bar:
      c: 3

production: 
  foo:
    bar:
      c: 4
```

Desired `values.yaml`:
```
a: 1
b: 2
foo:
  bar:
    c: 3
```

Using `print(yaml.dump(settings.as_dict()))` works for the top-level keys but the nested keys returned as *DynaBox* types.
