### ISSUE TITLE
Defining default values for some configuration parameters.

### ISSUE THREAD

**Issue by vladcalin** [rochacbruno/dynaconf#23]
I am wondering if there might be a method to define default values for configuration parameters for some values because they might not need to be required in some namespaces.

For example , I have a settings.yml file
```
DYNACONF:

DEVEL:
  MONGODB_DATABASE: devel
  MONGODB_HOST: localhost
  MONGODB_PORT: 27000

PRODUCTION:
  MONGODB_DATABASE: production_stuff
  MONGODB_HOST: mongodb.example.com
  MONGODB_PORT: 10980
  MONGODB_USERNAME: efe6398127928f1b2e9ef3207fb82663
  MONGODB_PASSWORD: 1f048e5fb80c559a4ab4c6e79d940708
```

And the username and password fields are not required in the devel namespace (can be `None`). 

If I attempt to get the `MONGODB_USERNAME` parameter from the `production` namespace, it works as expected but if I attempt to get it from the `DEVEL` namespace, it raises an `AttributeError` and I need to hack around it with ``getattr`` as shown.

```
print(settings.MONGODB_HOST)
print(settings.MONGODB_PORT)
print(settings.MONGODB_DATABASE)
print(getattr(settings, "MONGODB_USE_SSL", False))
print(getattr(settings, "MONGODB_USERNAME", None))
print(getattr(settings, "MONGODB_PASSWORD", None))
```

I understand if this is not a desired feature but it might come in really handy in some situations when we need some parameters in only one environment.

**Comment by rochacbruno** [comment]
@vladcalin settings is a `dict` like object, so when a default value is needed we can use `get`

I am using the following approach.

```python
print(settings.MONGODB_HOST)
print(settings.MONGODB_PORT)
print(settings.MONGODB_DATABASE)

print(settings.get('MONGODB_USE_SSL', default=False))
print(settings.get('MONGODB_USERNAME'))   # default is None
print(settings.get('MONGODB_PASSWORD'))
```

But if you want to define default values, another way would be using the global namespace `DYNACONF`

```YAML
DYNACONF:
    MONGODB_USE_SSL: false
    MONGODB_USERNAME: null
    MONGODB_PASSWORD: null

DEVEL:
  MONGODB_DATABASE: devel
  MONGODB_HOST: localhost
  MONGODB_PORT: 27000

PRODUCTION:
  MONGODB_DATABASE: production_stuff
  MONGODB_HOST: mongodb.example.com
  MONGODB_PORT: 10980
  MONGODB_USERNAME: efe6398127928f1b2e9ef3207fb82663
  MONGODB_PASSWORD: 1f048e5fb80c559a4ab4c6e79d940708
```

In that way when the value is not found in the specific namespace it is taken from the global.

```python

settings.namespace('devel')

# taken from DEVEL:
print(settings.MONGODB_HOST)  
print(settings.MONGODB_PORT)
print(settings.MONGODB_DATABASE)

# taken from DYNACONF: (the global namespace)
print(settings.MONGODB_USE_SSL)
print(settings.MONGODB_USERNAME)
print(settings.MONGODB_PASSWORD)
```
