### ISSUE TITLE
[RFC] Better merging standards

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#241]
Right now There are some ways for merging existing data structures in Dynaconf

- Using `dynaconf_merge` mark
- Using `__` double underlines for existing dictionaries and nested data
- Using MERGE_ENABLED_FOR_DYNACONF var to merge everything globally

All the 3 existing ways has limitations.

- `dynaconf_merge` is limited because it works only for 1st level vars
- `__` works only for data nested under a dictionary
- MERGE_ENABLED can break stuff in Django config.

# New standards for merging.

> **NOTE** All the above will keep working, we will try to not break backwards compatibility.

Although we are going to explicitly recommend only the new standards on explicit ways for merging that meets:

- Optional Granular control of which data is being merged
- Control of global merge feature per file
- Works also via environment variables
- Merge at any level in the nested structures
- Can merge any data type like dicts and lists

# The merge mark

Historically dynaconf is being using `@marks` for some special environment variables, we will introduce a new one: `@merge` for env vars and improve the existing `dynaconf_merge` for regular files.

## Merging files.

A `settings.yaml` file exists in your project:

```yaml
default:
  name: Bruno
  colors:
    - red
    - green
  data:
    links:
        twitter:  rochacbruno
        site: brunorocha.org
```

which will  add to `settings.__dict__` object data like:

```py
{
  "NAME": "Bruno",
  "COLORS": ["red", "green"],
  "DATA": {"links": {"twitter": "rochacbruno", "site": "brunorocha.org"}}
}
```

In a `settings.local.yaml` we want now to contribute to that existing data we have 2 options

### Merge the whole file

adding a `dynaconf_merge: true` to the root level of the file.

`settings.local.yaml`
```yaml
dynaconf_merge: true
default:
  colors:
    - blue
  data:
    links:
        github: rochacbruno.github.io
```

Then `settings.__dict__`

```py
{
  "NAME": "Bruno",
  "COLORS": ["red", "green", "blue"],
  "DATA": {"links": {"twitter": "rochacbruno", "site": "brunorocha.org", "github": "rochacbruno.github.io"}}
}
```

### Granular control of which variable is being merged

If we want to merge only specific variables we have to enclose data under a `dynaconf_merge` key, for example we want to override everything but we want to merge the colors.

`settings.local.yaml`
```yaml
default:
  name: Other Name
  colors:
    dynaconf_merge:
      - yellow
      - pink
  data:
    links:
        site: other.com
```

if it was `toml`

```toml
[default]
name = "Other Name"

[default.colors]
dynaconf_merge = ["yellow","pink"]

[default.data.links]
site = "other.com"
```

So dynaconf will do pre-processing of every file and for each `dynaconf_merge` it will call the merge pipeline.

Result on `settings.__dict__`
```py
{
  "NAME": "Other Name",  # <-- overwritten
  "COLORS": ["red", "green", "yellow", "pink"],  # <-- merged
  "DATA": {"links": {"site": "other.com"}}  # <-- overwritten
}
```
## Dunder merging

Dunder merging continues to work as a shortcut when the data you want to merge is behind a nested datastructure

```yaml
default:
  data__links__telegram: t.me/rochacbruno  # <-- Calls set('data.links', "t.me/rochacbruno")
```
or `toml`
```toml
[default]
data__links__telegram = "t.me/rochacbruno"  # <-- Calls set('data.links', "t.me/rochacbruno")
```

or `.env`

```bash
export DYNACONF_DATA__links__telegram="t.me/rochacbruno"  # <-- Calls set('data.links', "t.me/rochacbruno")
```

## @merge mark

For envvars the `@merge` will mark as it follows the standard for the other envvar markers.
and it can also be used in regular files

`.yaml`
```yaml
default:
  name: Jon # <-- Overwritten
  colors: "@merge blue"   # <-- Calls .append('blue')
  colors: "@merge ['blue', 'white']" # <-- Calls .extend(['blue', 'white'])
```

`.env`

```bash
export DYNACONf_NAME=Erik   # <-- Overwritten

export DYNACONF_COLORS="@merge ['blue']"   # <-- Calls .extend(['blue'])
export DYNACONF_COLORS="@merge ['blue', 'white']"  # <-- Calls .extend(['blue', 'white'])
export DYNACONF_COLORS="@merge blue"  # <-- Calls .append('blue')
export DYNACONF_COLORS="@merge blue,white"  # <-- Calls .extend('blue,white'.split(','))

export DYNACONF_DATA="@merge {foo='bar'}"  # <-- Calls .update({"foo": "bar"})
export DYNACONF_DATA="@merge foo=bar"  # <-- Calls ['foo'] = "bar"
```
