### ISSUE TITLE
Support multiple level in yml

### ISSUE THREAD

**Issue by Sytten** [rochacbruno/dynaconf#25]
Would be nice to support a more complex settings structure like:
```
PRODUCTION:
    DATABASE:
        HOST: ....
        PASSWORD: ...
```
And after use it like: ```settings.DATABASE.HOST```
Currently you get a dict at ```DATABASE```
