### ISSUE TITLE
What to do with declarations like "!!python/object/new:box.BoxList" ?

### ISSUE THREAD

**Issue by dmsimard** [rochacbruno/dynaconf#257]
We use dynaconf to template out a default configuration file in YAML and we've started seeing declarations like these:
```
default:
  ALLOWED_HOSTS: !!python/object/new:box.BoxList
    listitems:
    - ::1
    - 127.0.0.1
    - localhost
    state:
      box_class: &id001 !!python/name:box.Box ''
      box_options: {}
      box_org_ref: 140462933942512
```

I realize these are coming from python-box but they weren't present until recently.
They don't look mandatory ? A settings file without these seem to work as well.

It unfortunately makes the templated file less readable and definitely not human writable.
