### ISSUE TITLE
[bug] Yaml dumper is outputting python objects

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#311]
when running:

```bash
dynaconf list -o foo.yaml
```

I got this

```yaml
development:
  AGE: 15.5
  ANOTHERPATH: !!python/object:dynaconf.utils.parse_conf.LazyFormat
    formatter: !!python/name:dynaconf.utils.parse_conf.jinja_formatte
r ''
    token: jinja
    value: '{{ env.HOME | abspath }}'
  PATH: !!python/object:dynaconf.utils.parse_conf.LazyFormat
    formatter: !!python/object/apply:builtins.getattr
    - !!python/name:builtins.str ''
    - format
    token: format
    value: '{env[HOME]}/.databases/'
  USERNAME: Ferrabras
```

I expected to get:

```yaml
development:
  AGE: 15.5
  ANOTHERPATH: '@jinja {{ env.HOME | abspath }}'
  PATH: '@format {env[HOME]}/.databases/'
  USERNAME: Ferrabras
```
