### ISSUE TITLE
Variable reference 

### ISSUE THREAD

**Issue by telemmaite** [rochacbruno/dynaconf#359]
Is it currently possible to have variable referencing?
Just like here > https://github.com/vlucas/phpdotenv#nesting-variables

```php
BASE_DIR="/var/webroot/project-root"
CACHE_DIR="${BASE_DIR}/cache"
TMP_DIR="${BASE_DIR}/tmp"
```

I have item A and B.  Item A is very long and shares more than 90% of its configuration with B.
I would like to do something like:
```
default:
  item_a:
    name: 'A'
    ... many other fields
    ...
  item_b:  [extend item_a] 
    name: 'B'
    ... same other fields as A
```

**Comment by tarunwadhwa13** [comment]
I think this is what you need - https://dynaconf.readthedocs.io/en/latest/guides/usage.html#template-substitutions

**Comment by telemmaite** [comment]
Seems you are right, and my issue could be due to nesting, not sure why though.

**settings.yaml**
```yaml
development:
  template: "HELLO @tpl@"

  xxx:
    test: "@jinja {{this.TEMPLATE | replace('@tpl@','world')}}"
  test: "@jinja {{this.TEMPLATE | replace('@tpl@','world')}}"
```
**test.py**

```
from dynaconf import settings

print(settings.get('xxx').get('test'))
print(settings.get('test'))

>>> {{this.TEMPLATE | replace('@tpl@','world')}}
>>> HELLO world
```

Looks like if the template string is not on top level, it does not work.
Also noticed how dynaconf list reports them
```
Working in development environment 
TEMPLATE<str> 'HELLO @tpl@'
XXX<dict> {'test': '@jinja {{this.TEMPLATE | replace('@tpl@','world')}}'}
TEST<Lazy> '@jinja {{this.TEMPLATE | replace('@tpl@','world')}}'
```
