### ISSUE TITLE
Document  the usage with `python -m`

### ISSUE THREAD

**Issue by gopi1616** [rochacbruno/dynaconf#368]
My project structure:

gfa/
├── config
│   └── settings.yaml
├── __init__.py
├── __main__.py
├── resources
│   ├── exon_body.bed
│   ├── exon_end.bed
│   ├── exon_start.bed
├── src
│   ├── annotators
│   │   ├── get_annots.py
│   │   └── __init__.py
│   ├── gfa.py
│   ├── preprocess
└── tests
    ├── fixtures
    │   └── test_bkpt.tsv
    ├── __init__.py
    └── test_get_annots.py

I have a settings.yaml in the config folder with the content below
```yaml
---
exon_region_dict
  start : '../resources/exon_start.bed'
  stop : '../resources/exon_stop.bed'
  body : '../resources/exon_body.bed'
```
I call settings.EXON_REGION_DICT in get_annots.py but I get this error 
line 113, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'EXON_REGION_DICT'
