### ISSUE TITLE
[bug] LazyFormatted TypeError exception in Django TEMPLATES DIRS

### ISSUE THREAD

**Issue by dgavrilov** [rochacbruno/dynaconf#449]
**Describe the bug**
TypeError exception (expected str, bytes or os.PathLike object, not Lazy) if add templates dir path with `@format` or `@jinja` tokens.

**To Reproduce**

1. Having the following config files:

<details>
<summary> Config files </summary>

**.env**
```bash
DJANGO_ENV=development
DJANGO_SETTINGS_MODULE=project.settings
```

and

**settings.yaml**
```yaml
[default]
TEMPLATES:
    - APP_DIRS: true
      BACKEND: django.template.backends.django.DjangoTemplates
      DIRS:
        - "@format {this.BASE_DIR}/templates"
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages
```

</details>

2. Having the following app code:

<details>
<summary> Code </summary>

**settings.py**
```python
import os

import dynaconf

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

settings = dynaconf.DjangoDynaconf(__name__, BASE_DIR=BASE_DIR)
```

</details>

**Environment (please complete the following information):**
 - OS: Windows
 - Dynaconf version: 3.1.2
 - Frameworks: Django 2.2.16
