### ISSUE TITLE
[bug] Yaml Top Level Keys Not being Interpreted as Environments

### ISSUE THREAD

**Issue by vinayan3** [rochacbruno/dynaconf#516]
**Describe the bug**
Environments are not working with yaml files which had been working in dynaconf 2.2.3.

**To Reproduce**
1. Install dynaconf==3.1.2
2. Create file test.yaml
```
default:
  key: default-from-settings

development:
  key: dev-from-settings
  
production:
    key: production-from-settings
```
3. Create script test.py
```
import dynaconf
import pathlib
CONFIG_FILE_FOLDER = pathlib.Path(__file__).parent

Config = dynaconf.LazySettings(PRELOAD_FOR_DYNACONF=[str(CONFIG_FILE_FOLDER / 'test.yaml')])
Config.setenv('DEVELOPMENT')

print(Config.to_dict())
```
Output
```
{'DEFAULT': {'key': 'default-from-settings'}, 'DEVELOPMENT': {'key': 'dev-from-settings'}, 'PRODUCTION': {'key': 'production-from-settings'}}
```
**Expected behavior**
The script should output 
```
{'KEY': 'dev-from-settings'}
```
** Other Context**

I am basing the layered Yaml file from docs:
https://www.dynaconf.com/#layered-environments-on-files

I tried this in a docker image, python:slim-buster. It's the same result. 

**Environment (please complete the following information):**
 - OS: Ubuntu/18.04
 - Dynaconf Version 2.2.3
 - Frameworks in use: N/A
