### ISSUE TITLE
[RFC] Enable environments individually per file

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#543]
having 

```py
settings = Dynaconf(settings_files=["a.yaml", "b.toml"])
```
The file `a.yaml` will be loaded without taking environments in to account.

```yaml
---
name: Bruno
```

The file `b.toml` will be loaded considering environments because the special token `dynaconf_environments_enabled`

```toml
dynaconf_environments_enabled = true

[default]
name = "Jon"

[development]
name = "Mike"

[production]
name = "admin"

```
