### ISSUE TITLE
[bug] Unable to merge settings with environment variables

### ISSUE THREAD

**Issue by gmyrianthous** [rochacbruno/dynaconf#709]
**Describe the bug**
I have a dynaconf settings.yaml file with layered environments however, I am unable to overwrite/merge some of the parameters using environment variables. 

**To Reproduce**

1. Having the following config files:

<details>
<summary> Config files </summary>

**/path/.env**
```bash
Your .env content here
```

and

**/path/settings.yaml**
```yaml
default:

	PARAM_1: ''

	docker:
		some_config:
			config_a:
				some_param: 'cde'
				another_param: 'abc'
			config_b:
				different_param: 123
		PARAM_2: ''
		PARAM_3: ''


production:
	PARAM_1: 'param_1_for_prod'

	docker:
		PARAM_2: 'param2_for_prod'
		PARAM_3: 'param3_for_dev'

development:

	PARAM_1: 'param_1_for_dev'

	docker:
		PARAM_2: 'param2_for_dev'
		PARAM_3: 'param3_for_dev'	
```

</details>

2. Having the following app code:

<details>
<summary> Code </summary>

**/path/src/config.py**
```python
from dynaconf import settings

settings = Dynaconf(
    envvar_prefix='MY_APP',
    merge_enabled=True,
    environments=True,
    default_env='default',
    env='production',
    env_switcher='MY_APP_ENV',
    ignore_unknown_envvars=True,
    settings_files=['settings.yaml', '.secrets.yaml']
)
```

</details>

3. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
export MY_APP_DOCKER__PARAM_2=my_param
```

</details>

**Expected behavior**
I would  expect that the setting `settings.docker.PARAM_2` would  be equal  to `my_param`  but for some reason this does not work. 

The strange thing is that 

```bash
export MY_APP_PARAM_1=another_param
```

does work.

The  following also works, but for `PARAM_3` it does not. 
```bash
export MY_APP_DOCKER='@merge {PARAM_2=my_param}'
```

**Environment (please complete the following information):**
 - OS: OSX Big Sur (11.3)
 - Dynaconf Version: 3.1.5
 - Frameworks in use: -
 

**Additional context**

**Comment by gmyrianthous** [comment]
@rochacbruno Any thoughts on this?

**Comment by rwoloszyn** [comment]
@gmyrianthous Check     `ignore_unknown_envvars` in dynaconf config file. It messes up with os loaders.

**Comment by rochacbruno** [comment]
Ok, finally got time to work on this issue

Like @rwoloszyn said, ` ignore_unknown_envvars` will make dynaconf to ignore all the environment variables that was not already present on the settings file. this will make `DOCKER__PARAM_2` to be ignored.

Also your latest marge needs to be a valid toml dict

```bash
MY_APP_DOCKER='@merge {PARAM_3="my_param3"}'
```

> mind the quotes

I am adding a test case to ensure your case on 3.1.9

So conclusion:

```py
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix='MY_APP',
    merge_enabled=True,
    environments=True,
    env='development',
    settings_files=['settings.yaml'],
    load_dotenv=True
)


assert settings.foo == 'foo'
assert settings.param_1 == "my_param1"
assert settings.docker.param_2 == "my_param2"
assert settings.docker.param_3 == "my_param3", settings.docker.param_3
```
`settings.yaml`
```yaml
---
default:
  PARAM_1: ''
  docker:
    some_config:
      config_a:
        some_param: 'cde'
        another_param: 'abc'
      config_b:
        different_param: 123
    PARAM_2: ''
    PARAM_3: ''
development:
  PARAM_1: 'param_1_for_dev'
  docker:
    PARAM_2: 'param2_for_dev'
    PARAM_3: 'param3_for_dev'

```
`.env`
```bash
MY_APP_FOO=foo
MY_APP_PARAM_1=my_param1
MY_APP_DOCKER__PARAM_2=my_param2
MY_APP_DOCKER='@merge {PARAM_3="my_param3"}'
```

worked fine.
