### ISSUE TITLE
Allow config file to "extend" from other files

### ISSUE THREAD

**Issue by piglei** [rochacbruno/dynaconf#752]
While dynaconf supports including other files in a single config by using `dynaconf_include` variable, it's not good at sloving “extending and overwriting” problems.

For example, there are 2 config files. The first one is called `base.yaml`,  it contains plenty of common config values for my project:

```yaml
APP_CODE: code-a
APP_SECRET_KEY: some-secret
OTHER_COMMON_CONFIG: value
REQUEST_TIMEOUT: 30
```

Another file is `essential_overrides.yaml`, it's content is as below:

```YAML
REQUEST_TIMEOUT: 1
```

As you can see: `essential_overrides.yaml` is not designed to be used on it's own, it overrides a few essential config while most values should inherit from `base.yaml`.

To use `essential_overrides.yaml` as project config, we could try to use the `DYNACONF_INCLUDE` variable:

```YAML
REQUEST_TIMEOUT: 1
# Add “include” variable
DYNACONF_INCLUDE:
  - basic.yaml
```

Sadly, this won't work. Because files defined in `DYNACONF_INCLUDE` were loaded **after** regular settings files, So config defined in `basic.yaml` can never be overwrite by other files. In this case, `settings.get('REQUEST_TIMEOUT')` will be `30` instead of `1`.

Another workable solution is using multiple settings files. For example, by set “settings files” as below:

    export SETTINGS_FILES_FOR_DYNACONF="base.yaml;essential_overrides.yaml"

The problem can be solved. Although the “extending behavior” was specified in the “multiple settings files”, not some config variable in the file.

> The ["layered environments" feature](https://www.dynaconf.com/settings_files/#layered-environments-on-files) seems like a perfection solution for this problem. But in order to use this feature,  all config entries must be defined in a single big file. In some situations, it is not doable and it’s better to divide the configs into different files for different environments.

So, I was wondering that if it’s a good idea to implement a feature called “extending”. It will introduce a new special config attribute called “DYNACONF_EXTEND”. With it’s help, the `essential_overrides.yaml` can be updated as below:

```YAML
REQUEST_TIMEOUT: 1

# "extend" is different from "include". It allows you to override the original config
# values while “include” will always overwrite config variables in current file.
DYNACONF_EXTEND:
  - basic.yaml
```
