### ISSUE TITLE
RFC: Allow multiple settings files to be merged into one. 

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#86]
Targeting plugin based applications take as example:

Configuration for general program is in `export SETTINGS_FOR_DYNACONF=/etc/program/settings.ext` (`ext` being any of the supported formats yaml, json, ini, toml etc)

That same program has plugins and plugin stores its settings under different path like `/etc/plugin_name/settings.yaml`

## RFC: Allow `include` of settings files in different formats.

Then `/etc/program/settings.yaml`

```yaml
DEFAULT:
    DYNACONF_INCLUDE:
        - /etc/plugin_name/settings.yaml
        - /etc/other_plugin_name/settings.toml
        - /etc/settings_folder/* 
``` 

or toml

```toml
[default]
dynaconf_include = ["path1", "path2"]
```

or json

```json
{
   "default": {
        "dynaconf_include": ["path1", "path2"]
    }
}
```

then All the loaders will take the special `DYNACONF_INCLUDE` key then load values from each of the files listed using the normal pipeline.

### Requirements
- [x] Backwards compatibility
- [x] Multiple [envs] should be considered
- [x] Preserve the ordering
- [x] Nested includes should have a maximum recursion level
- [x] When the path is a directory, glob should be used and load in alpha order
- [x] All file formats should be supported, the functionality should be in BaseLoader
